# Generated by Django 4.1.2 on 2023-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=30)),
                ('time_of_workout', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('distance', models.IntegerField(default=0)),
                ('notes', models.TextField()),
            ],
        ),
    ]
